# Generated by Django 4.0.4 on 2022-05-31 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0002_group_alter_post_options_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='bulletin_board_app.group', verbose_name='Группа'),
        ),
    ]
